version: 2

models:
  - name: covid19_cases
    description: COVID-19 Dataset - see [this article](https://medium.com/starschema-blog/covid-19-and-the-first-war-of-data-science-980798f075ef) for more details.
    columns:
      - name: case_count
      - name: case_count_change
      - name: case_type
      - name: country_region
      - name: date
      - name: last_updated_date
      - name: latitude
      - name: longitude
      - name: province_state
