version: 2

models:
    - name: mrr_base
      description: Base model for Zuora MRR
      columns:
          - name: account_number
            tests:
                - not_null
          - name: account_name
            tests:
                - not_null
          - name: product_category
            description: Product category is based on the rate plan name.
            tests:
              - accepted_values:
                      values: ['GitHost', 'Other', 'Gold', 'Basic', 'Bronze', 'Premium', 'Starter', 'Ultimate', 'Support', 'Plus', 'Silver', 'Standard', 'Trueup']
          - name: rate_plan_charge_name
            tests:
                - not_null
    - name: gaap_revenue_base
      description: Base model for Zuora GAAP Revenue
      columns:
          - name: account_number
            tests:
                - not_null
          - name: account_name
            tests:
                - not_null
          - name: rate_plan_charge_name
            tests:
                - not_null
