version: 2

sources:
  - name: customers
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_postgres
    loader: Airflow

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: customers_db_customers
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
      - name: customers_db_eula_requests
        columns:
          - name: id
            tests:
              - not_null
          - name: eula_id
            tests:
              - not_null
      - name: customers_db_eulas
        columns:
          - name: id
            tests:
              - not_null
      - name: customers_db_license_seat_links
        columns:
          - name: zuora_subscription_id
          - name: order_id
            tests:
              - not_null
          - name: report_date
            tests:
              - not_null
      - name: customers_db_orders
        columns:
          - name: id
            tests:
              - not_null
      - name: customers_db_trial_histories
      - name: customers_db_versions
        columns:
          - name: id
            tests:
              - not_null
          - name: item_id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null