version: 2

models:
  - name: engineering_advisory_data
    description: '{{ doc("engineering_advisory_data") }}' 
    columns:
      - name: delta
      - name: filename
      - name: merge_date
      - name: package_type
      - name: publish_date
  - name: engineering_commit_stats
    description: This table details information about engineering commmit stats.
    columns:
      - name: commit_date
      - name: commit_id
  - name: engineering_nvd_data
    description: '{{ doc("engineering_nvd_data") }}'
    columns:
      - name: count
      - name: year
  - name: engineering_red_master_stats
    description: This table details data for when master has a red pipeline.
    columns:
      - name: backend_coverage
      - name: backend_coverage_absolute
      - name: backend_coverage_total
      - name: commit_date
      - name: jest_coverage
      - name: jest_coverage_absolute
      - name: jest_coverage_total
      - name: karma_coverage
      - name: karma_coverage_absolute
      - name: karma_coverage_total
  - name: engineering_part_of_product_merge_requests
    description: '{{ doc("engineering_product_merge_requests") }}'
    columns:
      - name: added_lines
      - name: real_size
      - name: removed_lines
      - name: plain_diff_url_path
        tests:
          - not_null
          - unique
  - name: engineering_development_team_members
    description: '{{ doc("engineering_development_team_members") }}'
    columns:
      - name: country
      - name: development_section
      - name: gitlab_handle
        tests:
          - not_null
          - unique
      - name: gitlab_id
        tests:
          - not_null
          - unique
      - name: is_backend_maintainer
      - name: is_backend_trainee_maintainer
      - name: is_database_maintainer
      - name: is_database_trainee_maintainer
      - name: is_frontend_maintainer
      - name: is_frontend_trainee_maintainer
      - name: is_manager
      - name: level
      - name: locality
      - name: location_factor
      - name: match_name
      - name: name
      - name: start_date
      - name: team
      - name: technology_group
    
