version: 2

models:
    - name: zuora_account_snapshots
      description: Source layer for Zuora Accounts Snapshots for cleaning and renaming
    - name: zuora_account_source
      description: Source layer for Zuora Accounts for cleaning and renaming
    - name: zuora_accounting_period_source
      description: Source layer for Zuora Accounting Periods for cleaning and renaming
      columns:
          - name: accounting_period_id
            tests:
                - not_null
          - name: accounting_period_start_date
            tests:
                - not_null
    - name: zuora_amendment_snapshots
      description: Source layer for Zuora Amendments Snapshots for cleaning and renaming
    - name: zuora_amendment_source
      description: Source layer for Zuora Amendments for cleaning and renaming
      columns:
        - name: amendment_id
          tests:
            - not_null
            - unique
    - name: zuora_contact_snapshots
      description: Source layer for Zuora Contacts Snapshots for cleaning and renaming
    - name: zuora_contact_source
      description: Source layer for Zuora Contacts for cleaning and renaming
    - name: zuora_discount_applied_metrics_source
      description: Source layer for Zuora Discount Applied Metrics  for cleaning and renaming
    - name: zuora_invoice_snapshots
      description: Source layer for Zuora Invoices Snapshots for cleaning and renaming
    - name: zuora_invoice_source
      description: Source layer for Zuora Invoices for cleaning and renaming
    - name: zuora_invoice_item_snapshots
      description: Source layer for Zuora Invoice Items Snapshots for cleaning and renaming
    - name: zuora_invoice_item_source
      description: Source layer for Zuora Invoice Items for cleaning and renaming
    - name: zuora_invoice_payment_source
      description: Source layer for Zuora Products for cleaning and renaming
      columns:
          - name: invoice_payment_id
            tests:
                - not_null
                - unique
          - name: invoice_id
            tests:
                - not_null
    - name: zuora_product_rate_plan_source
      description: Source layer for Zuora Product Rate Plans for cleaning and renaming
    - name: zuora_product_snapshots
      description: Source layer for Zuora Products Snapshots for cleaning and renaming
    - name: zuora_product_source
      description: Source layer for Zuora Products for cleaning and renaming
      columns:
          - name: product_id
            tests:
                - not_null
          - name: product_name
            tests:
                - not_null
    - name: zuora_rate_plan_snapshots
      description: Source layer for Zuora Rate Plans Snapshots for cleaning and renaming
    - name: zuora_rate_plan_source
      description: Source layer for Zuora Rate Plans for cleaning and renaming
    - name: zuora_rate_plan_charge_source
      description: Source layer for Zuora Rate Plan Charges for cleaning and renaming
    - name: zuora_refund_snapshots
      description: Source layer for Zuora Refunds Snapshots for cleaning and renaming
    - name: zuora_refund_source
      description: Source layer for Zuora Refunds for cleaning and renaming
    - name: zuora_revenue_schedule_item_snapshots
      description: Source layer for Zuora Revenue Schedule Item Snapshots for cleaning and renaming
    - name: zuora_revenue_schedule_item_source
      description: Source layer for Zuora Revenue Schedule Item for cleaning and renaming
      columns:
          - name: revenue_schedule_item_id
            tests:
               - not_null
          - name: rate_plan_charge_id
            tests:
               - not_null
          - name: accounting_period_id
            tests:
               - not_null
    - name: zuora_subscription_snapshots
      description: Source layer for Zuora Subscriptions Snapshots for cleaning and renaming
    - name: zuora_subscription_source
      description: Source layer for Zuora Subscriptions for cleaning and renaming
