version: 2
models:
    - name: ga360_session_custom_dimension
      description: Source model for GA Session Custom Dimensions
      columns:
        - name: visit_id
          tests:
            - not_null
    - name: ga360_session
      description: Source model for GA Sessions
      columns:
        - name: visit_id
          tests:
            - not_null
    - name: ga360_session_hit
      description: Source model for GA Sessions Hit
      columns:
        - name: visit_id
          tests:
            - not_null
