version: 2

models:
  - name: gitter_client_access
    description: '{{ doc("gitter_client_access") }}'
    columns:
      - name: id
      - name: env
      - name: event_at
      - name: user_id
      - name: client_id
      - name: client_name
      - name: client_key
      - name: client_tag
