version: '3.1'
services:
  db:
    container_name: bizops-dw
    build: .
    image: bizops/dw:dev
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
