version: 2

models:
    - name: zuora_account
      description: Base model for Zuora Accounts
      columns:
          - name: account_id
            tests:
                - not_null
                - unique
          - name: account_name
            tests:
                - not_null
    - name: zuora_contact
      description: Base model for Zuora contacts
      columns:
          - name: account_id
            tests:
                - not_null
          - name: contact_id
            tests:
                - not_null
                - unique
    - name: zuora_invoice
      description: Base model for Zuora invoices
      columns:
          - name: account_id
            tests:
                - not_null
          - name: invoice_id
            tests:
                - not_null
                - unique
    - name: zuora_rate_plan
      description: Base model for Zuora Rate Plans
      columns:
          - name: product_id
            tests:
                - not_null
          - name: rate_plan_id
            tests:
                - not_null
                - unique
    - name: zuora_rate_plan_charge
      description: Base model for Zuora Rate Plan Charges
      columns:
          - name: original_id
            tests:
                - not_null
          - name: rate_plan_id
            tests:
                - not_null
          - name: rate_plan_charge_id
            tests:
                - not_null
                - unique
    - name: zuora_subscription
      description: '{{ doc("zuora_subscription") }}'
      columns:
          - name: account_id
            tests:
                - not_null
          - name: contract_effective_date
            description: The field used to define a subscriptions cohort
          - name: subscription_id
            tests:
                - not_null
                - unique
          - name: subscription_status
            tests:
                - not_null
          - name: version
            description: Version as Zuora defines it. Not guaranteed to be unique.
