version: 2

models:
  - name: license_db_licenses
    description: This model is the data from tap-postgres for the licenses table from license.gitlab.com. This data represents the management of self-managed instances for GitLab customers.
    columns:
      - name: license_id
        tests:
          - not_null
          - unique
      - name: starts_at
        tests:
          - not_null
      - name: license_md5
        description: This column is an md5 hash of the `license_file` column from the `license` table. We do not import the the unhashed column for security/privacy reasons. This hashed value joins with usage pings from the version app.
  