name: 'gitlab_dw'
version: '1.0'

profile: 'gitlab'

source-paths: ["models"]

test-paths: ["tests"]

models:
  gitlab_dw:
    sfdc:
      base:
        enabled: true
        materialized: view
      transformed:
        enabled: true
        materialized: table

    pings:
      base:
        enabled: true
        materialized: view
      clean:
        enabled: true
        materialized: table


on-run-end:
  - 'GRANT SELECT ON ALL TABLES IN SCHEMA version TO tmurphy'
  - 'SELECT  zuora.calc_churn()'
