version: 2

models:
  - name: customers_db_charges_xf
    description: '{{ doc("customers_db_charges_xf") }}'
    columns:
      - name: subscription_name_slugify
        tests:
          - not_null
      - name: rate_plan_charge_id
        tests:
          - not_null
          - unique
      - name: is_purchased_through_subscription_portal
        description: From the subscription portal, a charge can either be purchased by a customer through the normal subscription portal checkout or activated via the admin interface by a GitLab team member. The charges that are started in the normal customer checkout have all the same `created_by_id` value '2c92a0fd55822b4d015593ac264767f2'

  - name: customers_db_trials
    description: '{{ doc("customers_db_trials") }}'
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null

  - name: latest_trial_per_namespace_xf
    description: '{{ doc("latest_trial_per_namespace_xf") }}'
    columns:
      - name: namespace_id
        tests:
          - not_null
          - unique
