version: 2

models:
    - name: qualtrics_contact_mailing_send
      description: 'All mailings sent to individual Qualtrics contacts, as well as the time in which they were sent.'
      columns:
        - name: contact_email
          tests:
            - not_null
        - name: mailing_sent_at
          tests:
            - not_null
        - name: survey_name
          tests:
            - not_null