version: 2
models:
- name: sheetload_certificates_unioned
  description: The collection of all certificates distributed by the Learning and Development team in the People group.
  columns:
  - name: date_completed
    description: The date the form was submitted.
    tests:
    - not_null
  - name: submitter_name
    description: The name of the submitter, if one was provided.
    tests:
    - not_null
  - name: correct_responses
    description: The number of correctly submitted responses.
    tests:
    - not_null
  - name: total_responses
    description: The number of total responses submited.
    tests:
    - not_null
  - name: is_team_member
    description: A boolean flag that looks for an `@gitlab.com` email address to identify if someone is a team member.
    tests:
    - not_null
  - name: submitter_email
    description: If the person is a team member, share their email; otherwise, this is a hash.
    tests:
    - not_null
  - name: certificate_name
    description: The name of the certificate- there are multiple kinds (Values, Ally, Certification, etc.)
    tests:
    - not_null
  - name: last_updated_at
    tests:
    - not_null

- name: hire_plan_xf
  description: This provides a data model of the headcount and hire planned by month broken into 3 levels - company, division, and department. This is for 2019.02 through 2020.04.
  columns:
    - name: month_date
    - name: breakout_type
      description: Identifies if the plan is at a department or division level, or aggregated up to all company.
    - name: department
    - name: division
    - name: planned_headcount
    - name: planned_hires
      description: This is calculated based on the difference between the month_date and the month prior.

- name: hire_replan_xf
  description: This provides a data model of the headcount and hire planned by month broken into 3 levels - company, division, and department. This combines the hire_plan_xf model for data between 2019.02 and 2020.04, and the rehire_plan has data from 2020.06 onwards..
  columns:
    - name: month_date
      tests:
        - not_null
    - name: breakout_type
      description: Identifies if the plan is at a department or division level, or aggregated up to all company.
      tests:
        - not_null
    - name: department
      tests:
        - not_null
    - name: division
      tests:
        - not_null
    - name: planned_headcount
    - name: planned_hires
      description: This is calculated based on the difference between the month_date and the month prior.      