version: 2

models:
  - name: sizes_part_of_product_merge_requests
    description: This table is a table of unique merge requests with data about the lines and files added/removed in the MR.
    columns:
    - name: product_merge_request_lines_added
    - name: product_merge_request_files_changed
    - name: product_merge_request_files_changed_truncated
    - name: product_merge_request_lines_removed
    - name: product_merge_request_project
      tests:
        - not_null
    - name: product_merge_request_id
      tests:
        - not_null
  - name: category_engineering_handbook_merge_requests
    description: This table is a table of unique merge requests to the handbook along with their categorization of a specific department/division in engineering.
    columns:
    - name: merge_request_state
      tests:
        - not_null
    - name: merge_request_edited_at
      tests:
        - not_null
    - name: plain_merge_request_diff_url_path
      tests:
        - not_null
        - unique
    - name: merge_request_department_list