version: 2

sources:
  - name: version
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: version_db_dump_stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: avg_cycle_analytics
        columns:
          - name: id
            tests:
              - not_null
      - name: conversational_development_indicies
        columns:
          - name: id
          - name: created_at
          - name: updated_at
      - name: fortune_companies
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
      - name: hosts
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
      - name: licenses
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
      - name: schema_migrations
      - name: usage_data
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
      - name: version_checks
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
      - name: users
      - name: versions
        columns:
          - name: id
            tests:
              - not_null
          - name: created_at
            tests:
              - not_null
          - name: updated_at
            tests:
              - not_null
