version: 2

sources:
  - name: covid19
    database: "COVID19"
    schema: public
    loader: Snowflake Data Exchange
    
    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: cases
        identifier: jhu_covid_19
        description: COVID-19 Dataset - see [this article](https://medium.com/starschema-blog/covid-19-and-the-first-war-of-data-science-980798f075ef) for more details.
        loaded_at_field: last_updated_date
