version: 2

models:
    - name: version_active_instances
      description: instances checked for new version or send a usage ping
      columns:
          - name: host_id
          - name: ping_type
            description: an instance checked for new version or send a usage ping

    - name: version_releases
      description: This model represents the different minor (X.y) versions released at GitLab.
      columns:
          - name: major_minor_version
            description: The `9.1` in 9.1.4, for example.
            tests:
              - not_null
              - unique
          - name: major_version
            description: The `9` in 9.1.4, for example.
            tests:
              - not_null
          - name: minor_version
            description: The `1` in 9.1.4, for example.
            tests:
              - not_null
          - name: release_date
            tests:
                - not_null
                - unique

    - name: version_usage_data_monthly_change
      description: '{{ doc("version_usage_data_monthly_change") }}'
      columns:
          - name: unique_key
            tests:
              - not_null
          - name: main_edition
            description: Comes from [this section of the code](https://gitlab.com/gitlab-org/gitlab/blob/2dae25c3b780205f072833cd290e481dae436f3b/lib/gitlab/usage_data.rb#L154)
            tests:
                - accepted_values:
                    values: ['EE', 'CE']

    - name: version_usage_data_unpacked
      description: '{{ doc("version_usage_data_unpacked") }}'
      columns:
          - name: days_after_version_release_date
            description: For the minor version that the instance is on, how many days ago was it first released?
          - name: latest_version_available_at_ping_creation
            description: What was the latest minor version available at the time of the usage ping?
          - name: main_edition
            description: Comes from [this section of the code](https://gitlab.com/gitlab-org/gitlab/blob/2dae25c3b780205f072833cd290e481dae436f3b/lib/gitlab/usage_data.rb#L154)
            tests:
                - accepted_values:
                    values: ['EE', 'CE']
          - name: uuid
            tests:
                - not_null
          - name: versions_behind_latest
            description: How many minor versions was the instance behind the latest version at the time of the ping?
          - name: zuora_subscription_id
            description: The Zuora subscription associated with the license sending the usage ping.

    - name: version_usage_data_weekly_opt_in_summary
      description: '{{ doc("version_usage_data_weekly_opt_in_summary") }}'
      tests:
        - unique:
            column_name: "concat(week, license_id)"
      columns:
          - name: week
            tests:
                - not_null
          - name: license_id
            tests:
                - not_null
          - name: license_md5
            tests:
                - not_null
          - name: product_category
            description: This is the plan (Starter, Premium, Ultimate) associated with the usage data. This is generally consistent with the License app, but has NULL values for many records that have plans in Zuora.
            
    - name: version_user_activity_by_stage_monthly_unpacked
      description: '{{ doc("version_user_activity_by_stage_monthly_unpacked") }}'
      columns:
          - name: main_edition
            description: Comes from [this section of the code](https://gitlab.com/gitlab-org/gitlab/blob/2dae25c3b780205f072833cd290e481dae436f3b/lib/gitlab/usage_data.rb#L154)
            tests:
                - accepted_values:
                    values: ['EE', 'CE']
          - name: uuid
            tests:
                - not_null
          - name: zuora_subscription_id
            description: The Zuora subscription associated with the license sending the usage ping.
