version: 2

models:
    - name: pipe2spend_consolidated
      description: '{{ doc("pipe2spend_consolidated") }}'
      columns:
          - name: month
            description: '{{ doc("pipe2spend_col_month") }}'
            tests:
                - not_null
          - name: pipe_name
            description: '{{ doc("pipe2spend_col_pipe_name") }}'
            tests:
                - not_null
          - name: pipe_type
            description: '{{ doc("pipe2spend_col_pipe_type") }}'
            tests:
                - not_null
          - name: pipe_iacv
            description: '{{ doc("pipe2spend_col_pipe_iacv") }}'
            tests:
                - not_null
          - name: headcount
            description: '{{ doc("pipe2spend_col_headcount") }}'
            tests:
                - not_null
          - name: salary_per_month
            description: '{{ doc("pipe2spend_col_salary_per_month") }}'
            tests:
                - not_null
          - name: spend
            description: '{{ doc("pipe2spend_col_spend") }}'
            tests:
                - not_null
          - name: pipe_to_spend
            description: '{{ doc("pipe2spend_col_pipe_to_spend") }}'
            tests:
                - not_null
