version: 2
models:
  - name: netsuite_entity_pii
    description: Model for Netsuite entities sensitive data
    columns:
        - name: entity_id
          tests:
            - not_null
            - unique
  - name: netsuite_subsidiaries_pii
    description: Model for Netsuite subsidiary sensitive data
    columns:
      - name: subsidiary_id
        tests:
          - not_null
          - unique
  - name: netsuite_transaction_lines_pii
    description: Model for Netsuite transaction lines sensitive data
    columns:
      - name: transaction_lines_unique_id
        tests:
          - not_null
          - unique
  - name: netsuite_vendors_pii
    description: Model for Netsuite vendors sensitive data
    columns:
      - name: vendor_id
        tests:
          - not_null
          - unique



