version: 2

sources:
  - name: engineering
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: engineering_extracts
    loader: Airflow
    
    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}

    tables:
      - name: advisory_data
        description: '{{ doc("engineering_advisory_data") }}'
      - name: commit_stats
        loaded_at_field: uploaded_at
      - name: nvd_data
        description: '{{ doc("engineering_nvd_data") }}'
      - name: red_master_stats
        loaded_at_field: uploaded_at
      - name: part_of_product_merge_requests
        description: '{{ doc("engineering_product_merge_requests") }}'
        loaded_at_field: uploaded_at
      - name: development_team_members
        description: '{{ doc("engineering_development_team_members") }}'
        loaded_at_field: uploaded_at
