version: 2

sources:
  - name: airflow
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: airflow_stitch
    loader: airflow
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: dag
      - name: dag_run