version: 2

models:
  - name: handbook_merge_requests
    description: '{{ doc("handbook_merge_requests") }}'
    columns:
      - name: file_diffs
      - name: merge_request_version_diffs
      - name: plain_diff_url_path
      - name: source_branch_name
