version: 2

models:
    - name: zendesk_ticket_audits
      description: This is the base model for Zendesk ticket audit events.
      columns:
      - name: audit_id
        tests:
            - not_null
      - name: ticket_id
        tests:
            - not_null    
    - name: zendesk_ticket_metrics
      description: This is the base model for Zendesk ticket metrics.
      columns:
      - name: ticket_id
        tests:
            - unique
            - not_null
      - name: ticket_metrics_id
        tests:
            - unique
            - not_null                  
