version: 2

models:
  - name: sfdc_accounts_xf
    description: '{{ doc("sfdc_accounts_xf") }}' 
    columns:
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null
  - name: sfdc_account_deal_size_segmentation
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: close_date
        tests:
          - not_null
      - name: deal_size
        tests:
          - not_null
  - name: sfdc_bizible_attribution_touchpoint_xf
    columns:
      - name: touchpoint_id
        tests:
          - not_null
          - unique
  - name: sfdc_campaign_xf
    columns:
      - name: campaign_id
        tests:
          - not_null
          - unique
  - name: sfdc_contact_xf
    columns:
      - name: contact_id
        tests:
          - not_null
          - unique
  - name: sfdc_executive_business_review_xf
    columns:
      - name: owner_id
        tests:
          - not_null
  - name: sfdc_lead_sources
    columns:
      - name: lead_source_id
        tests:
          - not_null
          - unique
      - name: initial_source
        tests:
          - not_null
      - name: initial_source_type
        tests:
          - not_null
  - name: sfdc_lead_xf
    description: '{{ doc("sfdc_lead_xf") }}'
    columns:
      - name: lead_id
        tests:
          - not_null
          - unique
  - name: sfdc_opportunity_field_historical 
    description: '{{ doc("sfdc_opportunity_field_historical") }}' 
    columns:
      - name: opportunity_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null 
  - name: sfdc_account_snapshot_history
    description: This model constrains the scope of sfdc_account_snapshots_base to the columns in sfdc_accounts_xf and their corresponding aliases.
    columns:
      - name: account_id
        tests:
          - not_null
      - name: account_name
        tests:
          - not_null            
      - name: valid_from
        tests: 
          - not_null                        
  - name: sfdc_opportunity_snapshot_history
    description: This model constrains the scope of sfdc_opportunity_snapshots_base to the columns in sfdc_opportunity_xf and their corresponding aliases.
    columns:
        - name: account_id
          tests:
            - not_null
        - name: opportunity_id
          tests:
            - not_null
        - name: opportunity_name
          tests:
            - not_null
        - name: stage_name
          tests:
            - not_null
        - name: valid_from
          tests: 
            - not_null                             
  - name: sfdc_opportunity_xf
    description: This model contains meta information on each Salesforce opportunity enriched with stage, source, and user information. Note that `sales_segment` and `parent_segment` are derived from the Stamped Sales Segment for an opportunity and do not change over time. The current segmentation of an opportunity's account is available in `sfdc_accounts_xf`.
    columns:
      - name: opportunity_id
        tests:
          - not_null
          - unique
      - name: owner_id
        description: The SFDC ID of opportunity owner.
        tests:
            - not_null
      - name: sales_segment
        tests:
          - accepted_values:
              values: ['SMB', 'Mid-Market', 'Strategic', 'Large', 'Unknown']
      - name: parent_segment
        tests:
          - accepted_values:
              values: ['SMB', 'Mid-Market', 'Strategic', 'Large', 'Unknown', Null]
  - name: sfdc_professional_services_engagement_xf
    columns:
      - name: ps_engagement_id
        tests:
          - not_null
          - unique          
  - name: sfdc_proof_of_value_xf
    columns:
      - name: pov_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('sfdc_account')
              field: account_id
      - name: opportunity_id
        tests:
          - relationships:
              to: ref('sfdc_opportunity_xf')
              field: opportunity_id
      - name: pov_status
        tests:
          - not_null
  - name: sfdc_sales_role_hierarchy
    description: This model contains a mapping of the user role hierarchy for all users in the Sales organization reporting to the CRO.
    columns:
      - name: id
        tests:
          - not_null
          - unique                               
  - name: sfdc_users_xf
    columns:
      - name: id
        tests:
          - not_null
          - unique       
