account: 
    constraints: 
        not_null: 
            - sfdc_account_id
            - type
        unique:
            - sfdc_account_id

dim_account:
    constraints:
        not_null:
            - id
            - sfdc_account_id
            - type
        unique:
            - id
            - sfdc_account_id

dim_leadsource:
    constraints:
        not_null:
            - id
        unique:
            - id

dim_opphistory:
    constraints:
        not_null:
            - opportunityid

dim_opportunitystage:
    constraints:
        not_null:
            - stage_id
            - sfdc_id
        unique:
            - stage_id
            - sfdc_id


f_opportunity:
    constraints:
        not_null:
            - opportunity_id
            - account_id
            - opportunity_stage_id
            - lead_source_id
            - ownerid

f_snapshot_opportunity:
    constraints:
        not_null:
            - opportunity_id
            - snapshot_date
            - account_id
            - opportunity_stage_id
            - lead_source_id
            - ownerid    

#leadsource: no tests here because this is a essentially a list

lineitems: 
    constraints:
        not_null:
            - id
            - opportunity_id
        unique:
            - id 

nolineitems:
    constraints:
        not_null:
            - id
            - opportunity_id
        unique:
            - id 

opplineitems:
    constraints:
        not_null:
            - id
            - opportunity_id
        unique:
            - id 

opportunity:
    constraints:
        not_null:
            - sfdc_id
            - ownerid
        unique:
            - sfdc_id

quotelineitems:
    constraints:
        not_null:
            - id
            - opportunity_id
        unique:
            - id

sfdc_account:
    constraints:
        not_null:
            - account_id
            - account_name
        unique:
            - account_id

sfdc_campaign:
    constraints:
        not_null:
            - campaign_id
            - campaign_name
        unique:
            - campaign_id

sfdc_opportunity:
    constraints:
        not_null:
            - opportunity_id
            - account_id
            - opportunity_name
        unique:
            - opportunity_id

sfdc_opportunityhistory:
    constraints:
        not_null:
            - id
            - opportunityid
        unique:
            - id

sfdc_opportunitystage:
    constraints:
        not_null:
            - stage_id
            - sfdc_id
        unique:
            - stage_id
            - sfdc_id

snapshot_opportunity:
    constraints:
        not_null:
            - sfdc_opportunity_id
            - snapshot_date
            - ownerid    

users:
    constraints:
        unique:
            - id