version: 2

models:
    - name: zendesk_group_memberships_source
      columns: 
        - name: group_membership_id
          tests:
            - not_null
            - unique
    - name: zendesk_groups_source
      columns:
        - name: group_id
          tests:
            - not_null
            - unique
    - name: zendesk_macros_source
      columns:
        - name: macro_id
          tests:
            - not_null
            - unique
    - name: zendesk_organizations_source
      description: This is the source model for Zendesk organizations.
      columns:
      - name: organization_id
        tests:
          - unique
          - not_null
      - name: arr
        description: This is the correction for AAR in organization fields. Field key cannot be changed in Zendesk.
    - name: zendesk_satisfaction_ratings_source
      columns:
        - name: satisfaction_rating_id
          tests:
            - not_null
            - unique
    - name: zendesk_tags_source
      columns:
        - name: tag_name
          tests:
            - not_null
            - unique   
    - name: zendesk_ticket_comments_source
      columns:
      - name: ticket_comment_id
        tests:
          - not_null
          - unique
    - name: zendesk_ticket_metrics_source
      description: This is the source model for Zendesk ticket metrics.
      columns:
      - name: ticket_id
        tests:
            - unique
            - not_null
      - name: ticket_metrics_id
        tests:
            - unique
            - not_null                  
    - name: zendesk_tickets_source
      description: This is the source model for Zendesk tickets.
      columns:
      - name: ticket_id
        tests:
            - unique
            - not_null
    - name: zendesk_users_source
      description: This is the source model for Zendesk users.
      columns:
      - name: user_id
        tests:
            - unique
            - not_null
