WITH usage_month AS (

    SELECT * FROM {{ ref('pings_usage_data_month') }}

)


SELECT
     DISTINCT *,
     {{ case_when_boolean_int("assignee_lists") }} AS assignee_lists_active,
     {{ case_when_boolean_int("auto_devops_disabled") }} AS auto_devops_disabled_active,
     {{ case_when_boolean_int("auto_devops_enabled") }} AS auto_devops_enabled_active,
     {{ case_when_boolean_int("boards") }} AS boards_active,
     {{ case_when_boolean_int("ci_builds") }} AS ci_builds_active,
     {{ case_when_boolean_int("ci_external_pipelines") }} AS ci_external_pipelines_active,
     {{ case_when_boolean_int("ci_internal_pipelines") }} AS ci_internal_pipelines_active,
     {{ case_when_boolean_int("ci_pipeline_config_auto_devops") }} AS ci_pipeline_config_auto_devops_active,
     {{ case_when_boolean_int("ci_pipeline_config_repository") }} AS ci_pipeline_config_repository_active,
     {{ case_when_boolean_int("ci_pipeline_schedules") }} AS ci_pipeline_schedules_active,
     {{ case_when_boolean_int("ci_runners") }} AS ci_runners_active,
     {{ case_when_boolean_int("ci_triggers") }} AS ci_triggers_active,
     {{ case_when_boolean_int("clusters") }} AS clusters_active,
     {{ case_when_boolean_int("clusters_applications_helm") }} AS clusters_applications_helm_active,
     {{ case_when_boolean_int("clusters_applications_ingress") }} AS clusters_applications_ingress_active,
     {{ case_when_boolean_int("clusters_applications_knative") }} AS clusters_applications_knative_active,
     {{ case_when_boolean_int("clusters_applications_prometheus") }} AS clusters_applications_prometheus_active,
     {{ case_when_boolean_int("clusters_applications_runner") }} AS clusters_applications_runner_active,
     {{ case_when_boolean_int("clusters_disabled") }} AS clusters_disabled_active,
     {{ case_when_boolean_int("clusters_enabled") }} AS clusters_enabled_active,
     {{ case_when_boolean_int("clusters_platforms_gke") }} AS clusters_platforms_gke_active,
     {{ case_when_boolean_int("clusters_platforms_user") }} AS clusters_platforms_user_active,
     {{ case_when_boolean_int("container_scanning_jobs") }} AS container_scanning_jobs_active,
     {{ case_when_boolean_int("dependency_scanning_jobs") }} AS dependency_scanning_jobs_active,
     {{ case_when_boolean_int("deploy_keys") }} AS deploy_keys_active,
     {{ case_when_boolean_int("deployments") }} AS deployments_active,
     {{ case_when_boolean_int("environments") }} AS environments_active,
     {{ case_when_boolean_int("epics") }} AS epics_active,
     {{ case_when_boolean_int("gcp_clusters") }} AS gcp_clusters_active,
     {{ case_when_boolean_int("geo_nodes") }} AS geo_nodes_active,
     {{ case_when_boolean_int("groups") }} AS groups_active,
     {{ case_when_boolean_int("in_review_folder") }} AS in_review_folder_active,
     {{ case_when_boolean_int("issues") }} AS issues_active,
     {{ case_when_boolean_int("keys") }} AS keys_active,
     {{ case_when_boolean_int("label_lists") }} AS label_lists_active,
     {{ case_when_boolean_int("labels") }} AS labels_active,
     {{ case_when_boolean_int("ldap_group_links") }} AS ldap_group_links_active,
     {{ case_when_boolean_int("ldap_keys") }} AS ldap_keys_active,
     {{ case_when_boolean_int("ldap_users") }} AS ldap_users_active,
     {{ case_when_boolean_int("lfs_objects") }} AS lfs_objects_active,
     {{ case_when_boolean_int("license_management_jobs") }} AS license_management_jobs_active,
     {{ case_when_boolean_int("merge_requests") }} AS merge_requests_active,
     {{ case_when_boolean_int("milestone_lists") }} AS milestone_lists_active,
     {{ case_when_boolean_int("milestones") }} AS milestones_active,
     {{ case_when_boolean_int("notes") }} AS notes_active,
     {{ case_when_boolean_int("pages_domains") }} AS pages_domains_active,
     {{ case_when_boolean_int("projects") }} AS projects_active,
     {{ case_when_boolean_int("projects_imported_from_github") }} AS projects_imported_from_github_active,
     {{ case_when_boolean_int("projects_jira_active") }} AS projects_jira_active_active,
     {{ case_when_boolean_int("projects_mirrored_with_pipelines_enabled") }} AS projects_mirrored_with_pipelines_enabled_active,
     {{ case_when_boolean_int("projects_prometheus_active") }} AS projects_prometheus_active_active,
     {{ case_when_boolean_int("projects_reporting_ci_cd_back_to_github") }} AS projects_reporting_ci_cd_back_to_github_active,
     {{ case_when_boolean_int("projects_slack_notifications_active") }} AS projects_slack_notifications_active_active,
     {{ case_when_boolean_int("projects_slack_slash_active") }} AS projects_slack_slash_active_active,
     {{ case_when_boolean_int("protected_branches") }} AS protected_branches_active,
     {{ case_when_boolean_int("releases") }} AS releases_active,
     {{ case_when_boolean_int("remote_mirrors") }} AS remote_mirrors_active,
     {{ case_when_boolean_int("sast_jobs") }} AS sast_jobs_active,
     {{ case_when_boolean_int("service_desk_enabled_projects") }} AS service_desk_enabled_projects_active,
     {{ case_when_boolean_int("service_desk_issues") }} AS service_desk_issues_active,
     {{ case_when_boolean_int("snippets") }} AS snippets_active,
     {{ case_when_boolean_int("todos") }} AS todos_active,
     {{ case_when_boolean_int("uploads") }} AS uploads_active,
     {{ case_when_boolean_int("web_hooks") }} AS web_hook_active
FROM usage_month