version: 2 

models:
  - name: mrr_totals_levelled
    description: '{{ doc("mrr_totals_levelled") }}'
    columns:
        - name: account_number
          description: '{{ doc("zuora_mrr_totals_col_account_number") }}'
        - name: subscription_name_slugify
          description: '{{ doc("zuora_mrr_totals_col_subscription_name_slugify") }}'
        - name: subscription_name
          description: '{{ doc("zuora_mrr_totals_col_subscription_name") }}'
        - name: subscription_slug_for_counting
          description: '{{ doc("zuora_mrr_totals_col_subscription_slug_for_counting") }}'
        - name: mrr_month
          description: '{{ doc("zuora_mrr_totals_col_mrr_month") }}'
        - name: cohort_month
          description: '{{ doc("zuora_mrr_totals_col_cohort_month") }}'
        - name: cohort_quarter
          description: '{{ doc("zuora_mrr_totals_col_cohort_quarter") }}'
        - name: months_since_cohort_start
          description: '{{ doc("zuora_mrr_totals_col_months_since_cohort_start") }}'
        - name: mrr_type    
          description: '{{ doc("zuora_mrr_totals_col_mrr_type") }}'
        - name: mrr
          description: '{{ doc("zuora_mrr_totals_col_mrr") }}'
          tests:
              - not_null
        - name: mrr_12mo_ago
          description: '{{ doc("zuora_mrr_totals_col_mrr_12mo_ago") }}'
        - name: ultimate_parent_account_id
          description: '{{ doc("sfdc_accounts_xf_col_ultimate_parent_account_id") }}'
        - name: ultimate_parent_account_name
          description: '{{ doc("sfdc_accounts_xf_col_ultimate_parent_account_name") }}'
        - name: quarters_since_cohort_start
          description: '{{ doc("zuora_mrr_totals_col_quarters_since_cohort_start") }}'
        - name: sub_row
          description: "The number of the subscription for the ultimate parent account, in order from the parent account's original cohort month. Ultimate parent accounts with multiple subscriptions starting in the same cohort month are given sequential numbers."
        - name: parent_account_cohort_month
          description: '{{ doc("mrr_totals_levelled_col_parent_account_cohort_month") }}'
        - name: parent_account_cohort_quarter
          description: '{{ doc("mrr_totals_levelled_col_parent_account_cohort_quarter") }}'
        - name: months_since_parent_cohort_start
          description: '{{ doc("mrr_totals_levelled_col_months_since_parent_cohort_start") }}'
        - name: quarters_since_parent_cohort_start
          description: '{{ doc("mrr_totals_levelled_col_quarters_since_parent_cohort_start") }}'

  - name: parent_account_mrr
    description: '{{ doc("parent_account_mrr") }}'
    columns:
        - name: distinct_id
          description: Primary Key
          tests:
              - not_null
              - unique
        - name: ultimate_parent_account_id
          description: '{{ doc("sfdc_accounts_xf_col_ultimate_parent_account_id") }}'
        - name: ultimate_parent_account_name
          description: '{{ doc("sfdc_accounts_xf_col_ultimate_parent_account_name") }}'
        - name: parent_account_cohort_month
          description: '{{ doc("mrr_totals_levelled_col_parent_account_cohort_month") }}'
        - name: parent_account_cohort_quarter
          description: '{{ doc("mrr_totals_levelled_col_parent_account_cohort_quarter") }}'
        - name: mrr_month
          description: '{{ doc("zuora_mrr_totals_col_mrr_month") }}'
        - name: months_since_parent_cohort_start
          description: '{{ doc("mrr_totals_levelled_col_months_since_parent_cohort_start") }}'
        - name: quarters_since_parent_cohort_start
          description: '{{ doc("mrr_totals_levelled_col_quarters_since_parent_cohort_start") }}'
        - name: mrr
          description: '{{ doc("zuora_mrr_totals_col_mrr") }}'
          tests:
              - not_null
        - name: mrr_12mo_ago
          description: '{{ doc("zuora_mrr_totals_col_mrr_12mo_ago") }}'


  - name: parent_account_mrr_agg
    description: '{{ doc("parent_account_mrr_agg") }}'
    columns:
        - name: mrr_month
          description: MRR Month
          tests:
            - not_null
        - name: net_rention
          description: Net Retention #add handbook link#
        - name: gross_retention
          description: Gross Retention #add handbook link#
