version: 2

models:
  - name: transformed_latest_location_factor_yaml
    description: This dbt model (view) just transforms the latest location factor yaml file to be able to join with the location application question answers.
    columns:
    - name: city
      tests:
        - not_null
    - name: state
      tests:
        - not_null
    - name: country
      tests: 
        - not_null
    - name: location_factor
      tests:
        - not_null
  - name: transformed_location_application_question_answers
    description: This dbt model (view) just transforms the location application question answers to be able to join with the latest location factor yaml file.
    columns:
    - name: city
      tests:
        - not_null
    - name: state
      tests:
        - not_null
    - name: country
      tests: 
        - not_null
