version: 2

sources:
  - name: team_yaml
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: team_yaml
    loader: Airflow
    loaded_at_field: uploaded_at

    freshness:
        warn_after: {count: 8, period: hour}

    tables:
      - name: team_yaml