version: 2

models:
  - name: direct_conversion
    description: '{{ doc("direct_conversion") }}'
    columns:
      - name: subscription_name_slugify
        tests:
            - not_null
      - name: subscription_month
        tests:
          - not_null
      - name: arr
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(subscription_name_slugify, delivery)"
  - name: free_to_paid
    description: '{{ doc("free_to_paid") }}'
    columns:
      - name: subscription_name_slugify
        tests:
            - not_null
      - name: subscription_month
        tests:
          - not_null
      - name: arr
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(subscription_name_slugify, delivery)"
