version: 2

models:
  - name: employee_location_factor_snapshots
    description: This captures changes in location factor for an employee
    columns:
      - name: bamboo_employee_number
        description: bamboo emp id
        tests:
          - not_null
          - unique
      - name: location_factor
        description: the location factor for the given time period
        tests:
          - not_null
      - name: event
        description: identifies the number of times location factor has been updated in source but doesn't necessarily equate to distinct changes
        tests:
          - not_null
      - name: min(valid_from)
        description: event start time
        tests:
          - not_null
     - name: max(valid_to)
        description: event end time
        tests:
          - not_null
        
