version: 2
models:
  - name: sfdc_account
    description: source model for SFDC Accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: account_name
        tests:
          - not_null
      - name: is_sdr_target_account
        tests:
          - not_null
  - name: sfdc_bizible_attribution_touchpoint
    description: Attribution touchpoints are on opportunities.
    columns:
        - name: touchpoint_id
          tests:
              - not_null
              - unique
        - name: campaign_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_campaign')
                    field: campaign_id
  - name: sfdc_bizible_touchpoint
    description: Touch points are on leads and contacts.
    columns:
        - name: touchpoint_id
          tests:
              - unique
              - not_null
  - name: sfdc_campaign
    description: source model for SFDC Campaigns
    columns:
        - name: campaign_id
          tests:
              - not_null
              - unique
        - name: campaign_name
          tests:
              - not_null
  - name: sfdc_campaign_member
    description: The source model for SFDC Campaign Members
    columns:
        - name: campaign_member_id
          tests:
              - not_null
              - unique
  - name: sfdc_contact
    description: source model for SFDC Contacts
    columns:
        - name: contact_id
          tests:
              - not_null
              - unique
  - name: sfdc_executive_business_review
    description: base model for SFDC Executive Business Reviews
    columns:
        - name: account_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_account')
                    field: account_id
        - name: ebr_id
          tests:
              - not_null
              - unique
        - name: ebr_date
          tests:
              - not_null
        - name: owner_id
          tests:
              - not_null
        - name: ebr_name
          tests:
              - not_null
  - name: sfdc_lead
    description: base model for SFDC Leads
    columns:
        - name: lead_id
          tests:
              - not_null
              - unique
        - name: sales_segmentation
          description: "Company size of the lead"
  - name: sfdc_opportunity
    description: base model for SFDC Opportunities
    columns:
        - name: account_id
          tests:
              - not_null
        - name: opportunity_id
          tests:
              - not_null
              - unique
        - name: opportunity_name
          tests:
              - not_null
        - name: stage_name
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_opportunity_stage')
                    field: primary_label
  - name: sfdc_opportunity_field_history
    description: base model for SFDC Opportunity Field History
    columns:
        - name: field_history_id
          tests:
              - not_null
        - name: opportunity_id
          tests:
              - not_null
  - name: sfdc_opportunity_stage
    description: base model for SFDC Opportunity Stages
    columns:
        - name: sfdc_id
          tests:
              - not_null
              - unique
  - name: sfdc_professional_services_engagement
    description: base model for SFDC Professional Services Engagements
    columns:
        - name: ps_engagement_id
          tests:
              - not_null
              - unique
        - name: opportunity_id
          tests:
              - not_null
              - relationships:
                    to: ref('sfdc_opportunity')
                    field: opportunity_id
  - name: sfdc_proof_of_value
    description: base model for SFDC Proof of Value
    columns:
        - name: account_id
          tests:
              - relationships:
                    to: ref('sfdc_account')
                    field: account_id
        - name: opportunity_id
          tests:
              - relationships:
                    to: ref('sfdc_opportunity')
                    field: opportunity_id
        - name: pov_id
          tests:
              - not_null
              - unique
        - name: pov_status
          tests:
              - not_null
  - name: sfdc_quote
    description: base model for SFDC Zuora Quotes
    columns:
        - name: quote_id
          tests:
              - not_null
              - unique
        - name: owner_id
          tests:
              - not_null
  - name: sfdc_record_type
    description: base model for SFDC Record Types
    columns:
        - name: record_type_id
          tests:
              - not_null
              - unique
        - name: record_type_name
          tests:
              - not_null
  - name: sfdc_user_roles
    description: base model for SFDC User Roles
    columns:
        - name: id
          tests:
              - not_null
              - unique

  - name: sfdc_users
    description: base model for SFDC Users
    columns:
        - name: id
          tests:
              - not_null
              - unique
