version: 2

models:
  - name: dim_customers
    description: '{{ doc("dim_customers") }}'
    columns:
      - name: crm_id
        description: account id from SFDC identifing the customer
        tests:
          - unique
      - name: customer_name
        description: account name from SFDC
      - name: customer_country
        description: billing country as in SFDC
      - name: ultimate_parent_account_id
        description: ultimate parent account id
      - name: ultimate_parent_account_name
        description: parent account name
      - name: ultimate_parent_account_country
        description: country of where the parent account is
      - name: is_deleted
        description: flag indicating if account has been deleted
      - name: merged_to_account_id
        description: for deleted accounts this is the SFDC account they were merged to

  - name: dim_dates
    columns:
      - name: date_id
        tests:
          - not_null
          - unique

  - name: dim_subscriptions
    description: "Dimension table representing subscription details as in Zuora"
    columns:
      - name: subscription_id
        tests:
          - not_null
          - unique
      - name: subscription_status
        tests:
          - not_null

  - name: dim_products
    description: "Product related information for which account is charged "
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: fct_invoice_items_agg
    description: "Aggregate fact table with invoice items summarized on charge level"
    columns:
      - name: charge_id
        tests:
          - not_null
          - unique

  - name: fct_charges
    description: "Factual table with all rate plan charges coming from subscriptions or an amendment to a subscription"
    columns:
      - name: subscription_id
        tests:
          - not_null




