version: 2

models:

  - name: dim_accounts
    description: "Dimension table representing each individual account with details of person to bill for the account. Excludes deleted and test accounts"
    columns:
      - name: account_id
        tests:
          - not_null
          - unique

  - name: dim_customers
    description: '{{ doc("dim_customers") }}'
    columns:
      - name: crm_id
        description: account id from SFDC identifing the customer
        tests:
          - unique
      - name: customer_name
        description: account name from SFDC
      - name: customer_country
        description: billing country as in SFDC
      - name: ultimate_parent_account_id
        description: ultimate parent account id
      - name: ultimate_parent_account_name
        description: parent account name
      - name: ultimate_parent_account_country
        description: country of where the parent account is
      - name: is_deleted
        description: flag indicating if account has been deleted
      - name: merged_to_account_id
        description: for deleted accounts this is the SFDC account they were merged to

  - name: dim_dates
    columns:
      - name: date_id
        tests:
          - not_null
          - unique

  - name: dim_subscriptions
    description: "Dimension table representing subscription details as in Zuora valid at give timestamp"
    columns:
      - name: subscription_id
        tests:
          - not_null
          - unique
      - name: subscription_status
        tests:
          - not_null

  - name: dim_product_details
    description: "Product related information."
    columns:
      - name: product_id
        tests:
          - not_null
      - name: is_reporter_license
        description: "Reporter licenses are in the Products with 'Additional Permission Types' in the name."
      - name: billing_list_price
        tests:
          - not_null
      - name: product_details_id
        tests:
          - unique
          - not_null
      - name: product_rate_plan_name
      - name: product_rate_plan_charge_name
      - name: product_name
      - name: product_sku
      - name: product_category
      - name: effective_start_date
      - name: effective_end_date
      - name: billing_list_price
    
  - name: fct_invoice_items
    description: '{{ doc("fct_invoice_items") }}'
    columns:
      - name: charge_id
        tests:
          - not_null
      - name: invoice_item_id
        tests:
          - not_null
          - unique
      - name: invoice_id
        tests:
          - not_null
      - name: invoice_number
      - name: invoice_account_id
      - name: invoice_date
      - name: service_start_date
      - name: service_end_date
      - name: invoice_amount_without_tax
      - name: invoice_item_charge_amount
      - name: invoice_item_unit_price

  - name: fct_invoice_items_agg
    description: "Aggregate fact table with invoice items summarized on charge level"
    columns:
      - name: charge_id
        tests:
          - not_null
          - unique

  - name: fct_charges
    description: "Factual table with all rate plan charges coming from subscriptions or an amendment to a subscription"
    columns:
      - name: subscription_id
        tests:
          - not_null
      - name: charge_id
        tests:
          - not_null
          - unique

  - name: dim_accounts_valid_at
    description: "Dimension table representing each individual account with details of person to bill for the account. Excludes deleted and test accounts"

  - name: dim_subscriptions_valid_at
    description: "Parameterized model to recreate dimension table representing subscription details as in Zuora at given date"

  - name: dim_products_valid_at
    description: "Parameterized model to recreate product related information for which account is charged at given date {valid_at}."

  - name: fct_charges_valid_at
    description: "Factual table with all rate plan charges coming from subscriptions or an amendment to a subscription "

  - name: fct_invoice_items_agg_valid_at
    description: "Parameterized model to recreate aggregate fact table with invoice items summarized on charge level at given date {valid_at}"

