version: 2

sources:
  - name: pmg
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: pmg
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 48, period: hour}

    tables:
    - name: paid_digital

