FROM fabiobatsilva/pentaho-data-integration:7.0.0-latest

LABEL maintainer "Aloysius Lim"
LABEL maintainer "Fabio B. Silva <fabio.bat.silva@gmail.com>"

COPY kettle/* $KETTLE_TEMPLATES/
COPY repo/ $PDI_PATH/repo/
