version: 2
models:
- name: sheetload_employee_location_factor
  description: This is the source of truth connecting an employee number from bamboo to the location factor used for People Ops purposes. The "Comp Data Analysis and Modeling" spreadsheet maintained by the Compensation & Benefits Manager is the SSOT for location factor.
  columns:
  - name: bamboo_employee_number
    description: Employee number is a front-facing number that peopleops can change. It is unique per employee and could in-theory change (but shouldn't).
    tests:
    - not_null
    - unique
  - name: location_factor
    description: This is the location factor used for calculating analyses and takes into account the metrics adjusted location factor, where that exists.
    tests:
    - not_null
- name: sheetload_headcount
  columns:
  - name: primary_key
    tests:
    - not_null
    - unique
- name: sheetload_planned_values
  description: Planned values for multiple metrics as defined by Finance Team via Chase
  columns:
    - name: primary_key
      tests:
      - not_null
      - unique
