version: 2

models:
    - name: ga360_session_custom_dimension_xf
      description: "Custom dimensions as found in Google Analytics Properties > Custom Definitions with their names"
      columns:
        - name: visit_id
          tests:
            - not_null
    - name: ga360_session_xf
      description: "https://support.google.com/analytics/answer/2731565?hl=en Including some custom dimensions"
      columns:
        - name: visit_id
          tests:
            - not_null