version: 2
models:
- name: sheetload_abm_account_baselines
- name: sheetload_abuse_mitigation
- name: sheetload_ally_certificate
- name: sheetload_calendar
- name: sheetload_certificates_unioned
  description: The collection of all certificates distributed by the Learning and Development team in the People group.
  columns:
  - name: date_completed
    description: The date the form was submitted.
    tests:
    - not_null
  - name: submitter_name
    description: The name of the submitter, if one was provided.
    tests:
    - not_null
  - name: correct_responses
    description: The number of correctly submitted responses.
    tests:
    - not_null
  - name: total_responses
    description: The number of total responses submited.
    tests:
    - not_null
  - name: is_team_member
    description: A boolean flag that looks for an `@gitlab.com` email address to identify if someone is a team member.
    tests:
    - not_null
  - name: submitter_email
    description: If the person is a team member, share their email; otherwise, this is a hash.
    tests:
    - not_null
  - name: certificate_name
    description: The name of the certificate- there are multiple kinds (Values, Ally, Certification, etc.)
    tests:
    - not_null
  - name: last_updated_at
    tests:
    - not_null
- name: sheetload_clari_forecast
- name: sheetload_communication_certificate
- name: sheetload_company_call_attendance
- name: sheetload_compensation_certificate
- name: sheetload_days_to_close
- name: sheetload_gitlab_slack_stats
- name: sheetload_google_referrals
- name: sheetload_headcount
- name: sheetload_hire_plan
- name: sheetload_job_roles_prior_to_2020_02
- name: sheetload_kpi_status
- name: sheetload_linkedin_recruiter
- name: sheetload_location_factor_targets
- name: sheetload_manual_downgrade_dotcom_tracking
- name: sheetload_marketing_core_users_from_docs_gitlab_com
- name: sheetload_marketing_kpi_benchmarks
- name: sheetload_osat
- name: sheetload_planned_values
- name: sheetload_procurement_cost_savings
- name: sheetload_release_blog_posts
- name: sheetload_rep_quotas_full_fy2020
- name: sheetload_rep_quotas_full_ps_fy2020
- name: sheetload_scalable_employment_values
- name: sheetload_social_marketing_metrics
- name: sheetload_values_certificate
- name: sheetload_yc_companies
    
