version: 2

sources:
  - name: bamboohr
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: bamboohr
    loader: Airflow
    loaded_at_field: uploaded_at
    
    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}

    tables:
      - name: compensation
      - name: custom_bonus
        identifier: custombonus
      - name: directory
      - name: employment_status
        identifier: employmentstatus
      - name: job_info
        identifier: jobinfo
      - name: id_employee_number_mapping
