version: 2

models:
  - name: greenhouse_recruiting_xf
    description: This is shows all applications submitted and ties in offer data, greenhouse department (the associated division), and source data to be in 1 place.
    columns:
        - name: application_id
        - name: offer_id
        - name: candidate_id
        - name: requisition_id
        - name: application_status
        - name: stage_name
        - name: offer_status
        - name: application_date
          description: The date the candidate applied for a specific job posting.
        - name: offer_sent_date
          description: The date the candidate was sent an offer
        - name:  offer_resolved_date
          description: The date the candidate either accepted or rejected the offer.
        - name: job_name
        - name: department_name
        - name: division
        - name: source_name
          description: Where the candidate came from 
        - name: source_type
        - name: sourcer_name
        - name: candidate_recruiter
        - name: candidate_coordinator
        - name: sourced_candidate
          description: Identifies if the source is LinkedIn(Prospecting)
        - name: time_to_offer
          description: Shows how long an applicant to go from applying to accepting an offer. This is based on offer accept month.
        - name: is_hired_in_bamboo
          description: This indicates if the candidate got hired and appears in bamboohr. 
  - name: greenhouse_diversity_intermediate
    description: This is the intermediate model used for greenhouse_diversity. It builds out a base that includes month_date, a column for all the various eeoc_field_names, and joins greenhouse_recruiting_xf to ensure each candidate is tied to an eeoc_field. In the event the candidate did not answer, the response is 'Did not identify'. This is later used in the greenhouse_diversity rpt to aggregate metrics.
    columns:
        - name: month_date
        - name: eeoc_field_name
          description: This column lists the eeoc_fields and ties it to each application. As a result, an applicant will have a response for gender, race, etc if it is null.                  
        - name: capture_month
          description: This identifies if the data is captured for the application month, the offer sent month, or offer_accepted. The metrics associated to these are grouped up in the greenhouse_diversity rpt.
        - name: application_id
        - name: department_name
        - name: division
        - name: division_modified
        - name: source_type
        - name: eeoc_values
          description: This field indicates the diversity for a candidate. For example, tying this to eeoc_field_name = 'Candidate_Gender' we can see the gender of the candidate if they choose to respond.
        - name: accepted_offer
          description: If the offer_status = 'accepted' then this will be a 1, otherwise 0. This is used later to aggregate offers in the greenhouse_diversity model.
        - name: time_to_offer
          description: Shows how long an applicant to go from applying to accepting an offer. This is based on offer accept month. 
        - name: sourced_candidate
          description: Candidates sourced through LinkedIn.
        - name: hired_sourced_candidates  
 
  - name: greenhouse_locations_cleaned_intermediate
    description: This dbt model partitions the area column from the location application question answers to get the city, state, and country of each location.
    columns:
      - name: job_post_id
      - name: application_id
        tests:
          - not_null
      - name: application_answer
        tests:
          - not_null
      - name: city
        tests:
          - not_null
      - name: state
        tests:
          - not_null
      - name: country
        tests: 
          - not_null  
      - name: application_question_answer_created_at
        tests:
          - not_null       

  - name: greenhouse_location_factors
    description: This dbt model gives the location factor of location application question answers. This is for data after 2019.07.22 as this is when we started capturing location factor historically.
    columns:
      - name: job_post_id
      - name: application_id
        tests:
          - not_null
      - name: application_answer
        tests:
          - not_null
      - name: city
        tests:
          - not_null
      - name: state
        tests:
          - not_null
      - name: country
        tests: 
          - not_null
      - name: location_factor
      - name: application_question_answer_created_at
        tests:
          - not_null 

  - name: greenhouse_stage_intermediate
    description: This data model shows all the greenhouse stages a candidate is in, and adds in additional information about the recruiting process such as source type, source name, recruiter, sourcer.
    columns:
        - name: unique_key
        - name: application_id
        - name: candidate_id
        - name: application_stage
        - name: is_milestone_stage
        - name: stage_entered_on
        - name: stage_exited_on
        - name: month_stage_entered_on
        - name: month_stage_exited_on
        - name: days_in_stage
        - name: days_in_pipeline
        - name: row_number_stages_desc
        - name: next_stage
        - name: is_current_stage
        - name: application_month
        - name: requisition_id
        - name: current_stage_name
        - name: application_status
        - name: job_name
        - name: department_name
        - name: division_modified
        - name: source_name
        - name: source_type
        - name: sourcer_name
        - name: candidate_recruiter
        - name: candidate_coordinator
        - name: rejection_reason_name
        - name: rejection_reason_type
        - name: current_job_req_status
        - name: is_hired_in_bamboo
        - name: time_to_offer
        - name: hit_application_review
        - name: hit_assessment
        - name: hit_screening
        - name: hit_team_interview
        - name: hit_reference_check
        - name: hit_offer
        - name: hit_hired
        - name: hit_rejected 
  - name: greenhouse_stage_analysis
    description: Provides the state of all candidates in our recruiting pipeline. This model is used to understand movement through the pipeline, bottlenecks and performance. The fields are the same as greenhouse_stage_intermediate but we have removed application_id and candidate_id and changed dates to month format.
  - name: greenhouse_location_factors_testing
    description: This is a temporary model used to allow the data team to clean up greenhouse locations and tie them to our location yaml file. Once greenhouse_location_factors has been cleaned this model needs to be removed.
    columns:
        - name: application_answer
          description: This is the answer as it appears in greenhouse.
        - name: city
          description: This is the cleaned city for the location answer.
        - name: state
          description: This is the cleaned state for the location answer.
        - name: country
          description: This is the cleaned country for the location answer.
        - name: application_question_answer_created_at
        - name: location_factor
          description: This is the mapped location factor based on the historical yaml file. We need to go through and identify how to map for cases it is missing.
  - name: greenhouse_sourcer
    description: This model is used to identify who the sourcer is for candidates. This is specific to source type = 'Prospecting'
  - name: greenhouse_hires
    description: This model is used to identify all greenhouse hires (including transfers within company). We want to capture the date the candidate truly started in bamboohr.
    columns:
        - name: application_id
        - name: candidate_id
        - name: region
          description: What area the hired candidate is in
        - name: greenhouse_candidate_row_number
          description: Indiciates the number of applications the candidate submitted and was hired for. For example, a 2 would be their second hire within the company.
        - name: hire_date_mod
          description: Note - this is a calculated field. In the case we don't have the candidate target hire date we are using the first record from the employment status table. If we do then we factor in the time between the candidate target hire and the bamboo hire date, and if it is less than 120 days we use the bamboo hire date, otherwise the targer_hire (the reason for this is because we don't have every application record for candidates hired prior to greenhouse. If this is the 2+ hired record in greenhouse we use the candidate target hire date as this candidate is a transfer.
        - name: hire_type
          description: Indicates whether the candidate is a hire, rehire, or transfer based on greenhouse_candidate_row_number.



