version: 2

sources:
  - name: dbt
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: dbt
    loader: airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 8, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: sources
      - name: run_results