version: 2

models:
    - name: qualtrics_distribution
      description: '{{ doc("qualtrics_distribution") }}'
      columns:
        - name: complaint_count
        - name: distribution_id
          tests:
            - not_null
        - name: email_blocked_count
        - name: email_bounced_count
        - name: email_failed_count
        - name: email_opened_count
        - name: email_sent_count
        - name: email_skipped_count
        - name: mailing_list_id
        - name: mailing_sent_at
          tests:
            - not_null
        - name: survey_id
          tests:
            - not_null
        - name: survey_finished_count
        - name: survey_started_count
        
    - name: qualtrics_survey
      description: '{{ doc("qualtrics_survey") }}'
      columns:
        - name: survey_id
          tests:
            - not_null
            - unique
        - name: survey_name
          tests:
            - not_null
    - name: qualtrics_mailing_contacts
      description: '{{ doc("qualtrics_mailing_contacts") }}'
      columns:
        - name: contact_email
          tests:
            - not_null
        - name: contact_id
          tests:
            - not_null
        - name: is_unsubscribed
          tests:
            - not_null
        - name: mailing_list_id
          tests:
            - not_null
        - name: mailing_list_membership_observed_at
          tests:
            - not_null
    - name: qualtrics_nps_survey_responses
      description: 'NPS Survey responses'
      columns:
        - name: response_id
          tests:
            - not_null
            - unique
        - name: response_values
    - name: qualtrics_question
      description: 'Data about Qualtrics survey questions'
      columns:
        - name: answer_choices
        - name: question_description
        - name: question_id
          tests:
            - not_null
            - unique
        - name: survey_id