version: 2

models:
  - name: arr_data_mart
    description: '{{ doc("arr_data_mart") }}'
    columns:
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: primary_key
        tests:
            - not_null
            - unique
  - name: arr_data_mart_incr
    description: '{{ doc("arr_data_mart_incr") }}'
    columns:
      - name: primary_key
        tests:
          - not_null
  - name: charges_agg
    description: "Base table used as a starting point for all charge analyses"
    columns:
      - name: charge_id
        tests:
            - not_null
            - unique
      - name: subscription_id
        tests:
            - not_null
      - name: is_last_segment_version
        description: "A rate plan charge can have multiple versions within a charge segment, similar to how a subscription can have multiple versions. The is_last_segment_version flag identifies the last version of a rate plan charge that was invoiced to the customer."
