version: 2

models:
  - name: sizes_part_of_product_merge_requests
    description: This table is a table of unique merge requests with data about the lines and files added/removed in the MR.
    columns:
    - name: product_merge_request_files_changed
    - name: product_merge_request_files_changed_truncated
    - name: product_merge_request_iid
      tests:
        - not_null
    - name: product_merge_request_lines_added
    - name: product_merge_request_lines_removed
    - name: product_merge_request_project
      tests:
        - not_null
    - name: product_merge_request_project_id
      tests:
        - not_null