version: 2

models:
  - name: category_handbook_engineering_merge_requests
    description: This dbt model (view) just filters category_handbook_merge_requests to only include engineering and support related MRs.
    columns:
    - name: merge_request_created_at
      tests:
        - not_null
    - name: merge_request_department_list
      tests:
        - not_null
    - name: merge_request_iid
      tests: 
        - unique
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      tests:
        - not_null
    - name: merge_request_updated_at
      tests:
        - not_null
  - name: category_handbook_merge_requests
    description: This is a dbt model (view) of unique merge requests to the handbook along with their categorization of a specific department/division in engineering.
    columns:
    - name: merge_request_created_at
      tests:
        - not_null
    - name: merge_request_department_list
      tests:
        - not_null
    - name: merge_request_iid
      tests: 
        - unique
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      tests:
        - not_null
    - name: merge_request_updated_at
      tests:
        - not_null
  - name: category_handbook_merge_requests_path_count
    description: This is a dbt model (view) of unique paths per merge requests to the handbook along with their categorization and count for each specific department/division in Engineering.
    columns:
    - name: merge_request_iid
      tests:
        - not_null
    - name: merge_request_path
      tests:
        - not_null
    - name: merge_request_state
      tests:
        - not_null
    - name: path_count_engineering
      tests:
        - not_null
    - name: path_count_ux
      tests:
        - not_null
    - name: path_count_security
      tests:
        - not_null
    - name: path_count_infrastructure
      tests:
        - not_null
    - name: path_count_development
      tests:
        - not_null
    - name: path_count_quality
      tests:
        - not_null
    - name: path_count_support
      tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      tests:
        - not_null






