version: 2

models:
  - name: gitter_active_users_client_access
    description: '{{ doc("gitter_active_users_client_access") }}'
    columns:
      - name: unique_key
      - name: user_id
      - name: date_actual
      - name: days_since_last_action
