version: 2

models:
  - name: license_db_add_ons_source
    description: This source model is the data from a bi-weekly export of the license-db-restore CloudSQL instance for the add_ons table from license.gitlab.com. This data represents license add-ons such as support packages.
    columns:
      - name: add_on_id
        tests:
          - not_null
          - unique

  - name: license_db_granted_add_ons_source
    description: This source model is the data from a bi-weekly export of the license-db-restore CloudSQL instance for the granted_add_ons table from license.gitlab.com. This data represents which add_ons are valid to which licenses.
    columns:
      - name: granted_add_on_id
        tests:
          - not_null
          - unique
      - name: license_id
        tests:
          - not_null
      - name: add_on_id
        tests:
          - not_null
          - relationships:
              to: ref('license_db_add_ons_source')
              field: add_on_id

  - name: license_db_licenses_source
    description: This source model is the data from from a bi-weekly export of the license-db-restore CloudSQL instance for the licenses table from license.gitlab.com. This data represents licenses and associated metadata such as expiration date and zuora subscription id.
    columns:
      - name: license_id
        tests:
          - not_null
          - unique
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: email
        meta:
          sensitive: true            
