version: 2

models:
  - name: customers_db_customers
    description: This model is the data from tap-postgres for the customers table from customers.gitlab.com. The schema of the database is defined in [this ruby code](https://gitlab.com/gitlab-org/customers-gitlab-com/blob/master/db/schema.rb).
  - name: customers_db_orders
    description: This model is the data from tap-postgres for the orders table from customers.gitlab.com. The schema of the database is defined in [this ruby code](https://gitlab.com/gitlab-org/customers-gitlab-com/blob/master/db/schema.rb).
  - name: customers_db_orders_with_incomplete_charges
    description: '{{ doc("customers_db_orders_with_incomplete_charges") }}'
  - name: customers_db_orders_with_valid_charges
    description: '{{ doc("customers_db_orders_with_valid_charges") }}'
  - name: customers_db_license_seat_links
    description: Self-managed EE instances will send seat link information to the customers portal on a daily basis. This information includes a count of active users and a maximum count of users historically in order to assist the true up process. Additional detail can be found in [this doc](https://gitlab.com/gitlab-org/customers-gitlab-com/-/blob/staging/doc/reconciliations.md).


